// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 8983 (Golem Lord Argelmach), 30 anchors over 420yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_8983()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 8983,
        {
            { 615.61f, -49.78f, -59.52f },
            { 609.53f, -54.98f, -59.52f },
            { 591.15f, -55.78f, -60.04f },
            { 582.68f, -56.12f, -60.01f },
            { 584.82f, -62.43f, -55.45f },
            { 591.66f, -67.39f, -50.54f },
            { 605.85f, -77.32f, -45.50f },
            { 620.65f, -88.52f, -45.60f },
            { 629.38f, -105.03f, -45.40f },
            { 638.45f, -119.72f, -45.72f },
            { 654.23f, -128.79f, -45.70f },
            { 671.10f, -135.60f, -45.72f },
            { 679.52f, -138.08f, -45.72f },
            { 688.94f, -136.20f, -45.70f },
            { 701.74f, -125.35f, -45.17f },
            { 714.52f, -112.91f, -45.60f },
            { 726.72f, -100.79f, -45.59f },
            { 738.97f, -88.36f, -45.19f },
            { 749.69f, -75.75f, -45.66f },
            { 755.98f, -67.42f, -45.72f },
            { 754.17f, -49.61f, -45.63f },
            { 749.11f, -31.60f, -45.69f },
            { 747.01f, -22.87f, -45.72f },
            { 733.63f, -10.75f, -45.52f },
            { 724.60f, -4.91f, -45.58f },
            { 721.32f, 11.96f, -44.17f },
            { 730.76f, 18.00f, -47.27f },
            { 739.07f, 19.04f, -51.67f },
            { 758.14f, 19.40f, -53.15f },
            { 775.69f, 16.16f, -53.12f },
        });
}
