// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9016 (Bael'Gar), 21 anchors over 294yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9016()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9016,
        {
            { 527.97f, -54.21f, -61.67f },
            { 544.65f, -52.48f, -63.35f },
            { 553.19f, -51.59f, -61.19f },
            { 561.60f, -41.93f, -60.89f },
            { 564.85f, -25.47f, -65.27f },
            { 566.39f, -5.96f, -70.23f },
            { 573.03f, -1.15f, -69.84f },
            { 572.48f, 7.76f, -69.83f },
            { 578.10f, 14.45f, -70.56f },
            { 588.73f, 16.72f, -70.45f },
            { 590.57f, 26.58f, -72.27f },
            { 605.56f, 33.45f, -73.05f },
            { 623.44f, 35.04f, -73.30f },
            { 628.96f, 54.53f, -72.78f },
            { 632.08f, 70.66f, -72.91f },
            { 641.80f, 75.82f, -72.94f },
            { 653.08f, 90.69f, -73.25f },
            { 657.73f, 106.77f, -72.82f },
            { 666.62f, 120.99f, -72.87f },
            { 676.08f, 139.00f, -72.80f },
            { 687.27f, 153.28f, -72.12f },
        });
}
