// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9033 (General Angerforge), 15 anchors over 212yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9033()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9033,
        {
            { 600.08f, -189.43f, -53.62f },
            { 594.04f, -173.38f, -52.98f },
            { 589.46f, -155.34f, -52.03f },
            { 586.76f, -139.49f, -52.21f },
            { 586.50f, -122.87f, -48.86f },
            { 585.40f, -106.33f, -45.04f },
            { 593.33f, -102.65f, -44.67f },
            { 611.25f, -102.97f, -44.74f },
            { 628.05f, -105.19f, -45.89f },
            { 634.79f, -116.43f, -45.70f },
            { 649.86f, -124.24f, -45.72f },
            { 660.62f, -130.37f, -71.73f },
            { 676.70f, -125.10f, -72.10f },
            { 670.54f, -110.06f, -71.17f },
            { 667.04f, -102.72f, -70.98f },
        });
}
