// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 1325400066 (Shadowforge Lock), 13 anchors over 188yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_1325400066()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 1325400066,
        {
            { 484.10f, 23.29f, -69.19f },
            { 499.13f, 14.49f, -69.75f },
            { 516.97f, 10.61f, -69.85f },
            { 533.58f, 7.00f, -68.65f },
            { 550.25f, 3.38f, -68.16f },
            { 566.04f, -1.14f, -69.67f },
            { 565.83f, -19.63f, -67.01f },
            { 562.36f, -38.30f, -61.80f },
            { 560.86f, -46.42f, -60.10f },
            { 568.53f, -53.12f, -59.40f },
            { 585.87f, -53.39f, -59.44f },
            { 602.78f, -51.67f, -59.51f },
            { 614.55f, -49.94f, -59.52f },
        });
}
