// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9056 (Fineous Darkvire), 6 anchors over 71yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9056()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9056,
        {
            { 901.36f, -279.79f, -71.32f },
            { 916.77f, -290.27f, -71.22f },
            { 931.01f, -300.20f, -71.56f },
            { 938.52f, -304.28f, -71.75f },
            { 934.01f, -312.31f, -71.22f },
            { 946.39f, -325.41f, -71.76f },
        });
}
