// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9319 (Houndmaster Grebmar), 29 anchors over 431yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9319()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9319,
        {
            { 310.56f, -146.25f, -70.39f },
            { 322.93f, -133.20f, -67.94f },
            { 331.08f, -134.37f, -64.82f },
            { 348.81f, -134.55f, -64.42f },
            { 365.17f, -131.69f, -64.42f },
            { 381.91f, -128.40f, -64.42f },
            { 399.17f, -124.56f, -64.48f },
            { 415.63f, -120.79f, -65.12f },
            { 433.38f, -116.85f, -64.69f },
            { 451.20f, -113.39f, -63.73f },
            { 469.49f, -115.36f, -62.76f },
            { 488.52f, -118.78f, -62.00f },
            { 508.69f, -116.34f, -62.27f },
            { 517.38f, -122.43f, -62.64f },
            { 534.98f, -125.21f, -61.28f },
            { 543.26f, -124.47f, -61.67f },
            { 560.89f, -128.07f, -61.53f },
            { 576.87f, -133.18f, -65.11f },
            { 588.62f, -135.17f, -67.91f },
            { 589.32f, -126.62f, -68.00f },
            { 599.31f, -125.81f, -68.49f },
            { 613.95f, -137.80f, -70.86f },
            { 627.14f, -148.61f, -71.58f },
            { 640.39f, -158.18f, -70.46f },
            { 649.28f, -174.35f, -72.22f },
            { 650.55f, -191.93f, -75.82f },
            { 652.00f, -208.88f, -77.30f },
            { 651.21f, -217.19f, -79.71f },
            { 646.17f, -224.37f, -82.37f },
        });
}
