// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 9017 (Lord Incendius), 33 anchors over 517yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_9017()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 9017,
        {
            { 595.46f, -72.46f, -49.04f },
            { 583.19f, -61.86f, -56.71f },
            { 574.52f, -57.94f, -60.00f },
            { 559.77f, -48.63f, -60.55f },
            { 564.13f, -29.35f, -64.52f },
            { 568.11f, -12.89f, -69.92f },
            { 577.61f, 2.06f, -70.19f },
            { 583.03f, 8.84f, -68.89f },
            { 591.20f, 10.61f, -70.00f },
            { 607.71f, 3.53f, -72.53f },
            { 620.74f, -7.85f, -73.49f },
            { 633.45f, -20.12f, -73.24f },
            { 645.52f, -31.77f, -73.25f },
            { 657.89f, -43.72f, -73.30f },
            { 670.48f, -55.88f, -72.95f },
            { 682.88f, -67.86f, -72.38f },
            { 695.62f, -80.43f, -72.20f },
            { 708.06f, -92.73f, -71.40f },
            { 719.91f, -104.46f, -71.73f },
            { 731.70f, -116.12f, -71.83f },
            { 748.12f, -127.76f, -72.39f },
            { 762.03f, -137.42f, -72.87f },
            { 771.26f, -140.72f, -73.13f },
            { 768.71f, -151.05f, -73.30f },
            { 781.24f, -163.46f, -73.27f },
            { 790.92f, -179.82f, -73.49f },
            { 801.89f, -196.16f, -72.75f },
            { 818.19f, -207.87f, -72.02f },
            { 831.42f, -219.15f, -71.63f },
            { 844.25f, -230.08f, -71.28f },
            { 857.39f, -243.87f, -71.22f },
            { 871.37f, -253.68f, -71.22f },
            { 877.96f, -258.98f, -71.26f },
        });
}
