// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 230, boss 1325400065 (Ring of Law), 12 anchors over 180yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute230_1325400065()
{
    DungeonClearRouteRegistry::Register(230, DUNGEON_DIFFICULTY_NORMAL, 1325400065,
        {
            { 520.13f, -85.31f, -62.07f },
            { 518.85f, -103.54f, -61.64f },
            { 517.65f, -120.60f, -62.38f },
            { 516.24f, -140.60f, -62.23f },
            { 516.80f, -160.99f, -60.55f },
            { 522.16f, -178.64f, -57.91f },
            { 534.87f, -197.51f, -55.70f },
            { 543.38f, -202.54f, -54.70f },
            { 551.33f, -200.97f, -52.72f },
            { 559.92f, -194.11f, -52.04f },
            { 582.94f, -194.48f, -52.94f },
            { 594.17f, -195.73f, -53.26f },
        });
}
