-- Replace residual English NPC names in zhCN quest text only when the NPC is structurally linked to that quest and has an unambiguous existing zhCN name.
-- Excludes names that also identify item templates, avoiding NPC/item homonym replacements.
-- Generated from current tw_world relations and locales on 2026-09-11.

UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Yenniku','耶尼库') WHERE `entry` = 593;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Chief Hawkwind','鹰风酋长') WHERE `entry` = 755;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Chief Hawkwind','鹰风酋长') WHERE `entry` = 763;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Mangletooth','碎牙') WHERE `entry` = 889;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathandris Silversky','阿拉珊蒂丝·银空') WHERE `entry` = 4107;
UPDATE `locales_quest` SET `Title_loc4` = REPLACE(`Title_loc4`,'A-Me 01','艾米01'), `Details_loc4` = REPLACE(`Details_loc4`,'A-Me 01','艾米01'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'A-Me 01','艾米01') WHERE `entry` = 4243;
UPDATE `locales_quest` SET `Title_loc4` = REPLACE(`Title_loc4`,'A-Me 01','艾米01'), `Details_loc4` = REPLACE(`Details_loc4`,'A-Me 01','艾米01'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'A-Me 01','艾米01') WHERE `entry` = 4244;
UPDATE `locales_quest` SET `Title_loc4` = REPLACE(`Title_loc4`,'A-Me 01','艾米01'), `Details_loc4` = REPLACE(`Details_loc4`,'A-Me 01','艾米01'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'A-Me 01','艾米01') WHERE `entry` = 4245;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Thalia Amberhide','萨利亚') WHERE `entry` = 4904;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Mangletooth','碎牙') WHERE `entry` = 5044;
UPDATE `locales_quest` SET `ObjectiveText2_loc4` = REPLACE(`ObjectiveText2_loc4`,'Eva Sarkhoff','艾瓦·萨克霍夫') WHERE `entry` = 5382;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Field Marshal Teravaine','指挥官特拉瓦雷') WHERE `entry` = 6846;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Warmaster Garrick','突击队长加瑞克') WHERE `entry` = 6901;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 7789;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 7874;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 7875;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 7876;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Kerri Hicks','克莉·希克斯') WHERE `entry` = 7889;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Kerri Hicks','克莉·希克斯') WHERE `entry` = 7892;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sergeant Maclear','玛克里尔中士') WHERE `entry` = 8081;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Al''tabim the All-Seeing','全知者阿塔比姆') WHERE `entry` = 8109;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Maywiki of Zuldazar','祖达萨的梅维克') WHERE `entry` = 8116;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Maywiki of Zuldazar','祖达萨的梅维克') WHERE `entry` = 8117;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deathstalker Mortis','亡灵哨兵莫提斯') WHERE `entry` = 8124;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sergeant Maclear','玛克里尔中士') WHERE `entry` = 8157;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sergeant Maclear','玛克里尔中士') WHERE `entry` = 8158;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sergeant Maclear','玛克里尔中士') WHERE `entry` = 8159;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deathstalker Mortis','亡灵哨兵莫提斯') WHERE `entry` = 8163;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deathstalker Mortis','亡灵哨兵莫提斯') WHERE `entry` = 8164;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deathstalker Mortis','亡灵哨兵莫提斯') WHERE `entry` = 8165;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 8267;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sentinel Farsong','哨兵轻歌') WHERE `entry` = 8269;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Captain Shatterskull','沙塔尔·碎颅') WHERE `entry` = 8294;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Sergeant Maclear','玛克里尔中士') WHERE `entry` = 8298;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deathstalker Mortis','亡灵哨兵莫提斯') WHERE `entry` = 8300;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Darkcaller Yanka','黑暗召唤者雅恩卡') WHERE `entry` = 8409;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Twilight Marauder Morna','暮光掠夺者莫娜') WHERE `entry` = 8740;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Anachronos','安纳克罗斯'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Anachronos','安纳克罗斯') WHERE `entry` = 8741;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Isalien''s','依萨利恩的') WHERE `entry` = 8967;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Isalien''s','依萨利恩的') WHERE `entry` = 8990;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Kormok','库尔莫克') WHERE `entry` = 8992;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(REPLACE(`Objectives_loc4`,'Anachronos','安纳克罗斯'),'Atiesh','埃提耶什'), `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Atiesh','埃提耶什') WHERE `entry` = 9269;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Atiesh','埃提耶什') WHERE `entry` = 9270;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(REPLACE(`Objectives_loc4`,'Anachronos','安纳克罗斯'),'Atiesh','埃提耶什'), `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Atiesh','埃提耶什') WHERE `entry` = 9271;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Nargal Deatheye','纳加尔·死眼') WHERE `entry` = 39995;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Nargal Deatheye','纳加尔·死眼') WHERE `entry` = 39996;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Birgitte Cranston','比尔吉特·克兰斯顿'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Birgitte Cranston','比尔吉特·克兰斯顿') WHERE `entry` = 39997;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Mishiki','米什基'), `OfferRewardText_loc4` = REPLACE(REPLACE(`OfferRewardText_loc4`,'Mishiki','米什基'),'Shagu','煞古') WHERE `entry` = 40001;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Magtoor','玛格图尔') WHERE `entry` = 40030;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Gigno Flaxwhisker','吉格诺·麻须'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Gigno Flaxwhisker','吉格诺·麻须') WHERE `entry` = 40040;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Gigno Flaxwhisker','吉格诺·麻须') WHERE `entry` = 40041;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Lorie Gearwatch','罗利·齿钟') WHERE `entry` = 40045;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Gigno Flaxwhisker','吉格诺·麻须') WHERE `entry` = 40046;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Tinkmaster Overspark','工匠大师欧沃斯巴克') WHERE `entry` = 40047;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(REPLACE(`Objectives_loc4`,'Tinkmaster Overspark','工匠大师欧沃斯巴克'),'Gigno Flaxwhisker','吉格诺·麻须') WHERE `entry` = 40048;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Bessy','贝希') WHERE `entry` = 40056;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Fendo Wobblefizz','芬多·胀气') WHERE `entry` = 40066;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Fendo Wobblefizz','芬多·胀气') WHERE `entry` = 40067;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Janet Hollowworth','珍妮特·霍洛沃斯') WHERE `entry` = 40073;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Clarise Gnarltree','克拉莉斯·纳尔特里') WHERE `entry` = 40074;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Marlow Neggle','玛洛·奈格尔') WHERE `entry` = 40086;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Denatharion','德纳萨里安') WHERE `entry` = 40091;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Deckmaster Breachcrest','甲板长布瑞驰克莱斯特') WHERE `entry` = 40093;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Ardaen Evermoon','阿丁·永月') WHERE `entry` = 40120;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Eliza Caldwell','伊莉莎·考德沃') WHERE `entry` = 40150;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Hydromancer Flakereef','水术师弗雷克利夫') WHERE `entry` = 40163;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Hydromancer Flakereef','水术师弗雷克利夫') WHERE `entry` = 40167;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Flaz Fusemix','弗雷泽·缠线') WHERE `entry` = 40177;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Thirael Blistersong','塞瑞尔·疱歌') WHERE `entry` = 40184;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Blazno Blastpipe','布雷兹诺·布拉斯派普') WHERE `entry` = 40189;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Blazno Blastpipe','布雷兹诺·布拉斯派普') WHERE `entry` = 40190;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Tarokar','塔罗卡') WHERE `entry` = 40191;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Jubo','诸波') WHERE `entry` = 40195;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Daela Evermoon','迪拉·永月') WHERE `entry` = 40197;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Blatarg','布莱塔格') WHERE `entry` = 40200;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Adaena Oakleaf','阿迪那·木叶'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Adaena Oakleaf','阿迪那·木叶') WHERE `entry` = 40204;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Thultash','索尔塔什') WHERE `entry` = 40206;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Embergut','烬腹'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Embergut','烬腹') WHERE `entry` = 40217;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Seer Borgorr','先知宝高') WHERE `entry` = 40218;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Morpheus Ribcage','墨菲斯·肋骨') WHERE `entry` = 40220;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Strahad Farsan','斯坦哈德·法尔杉'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Strahad Farsan','斯坦哈德·法尔杉') WHERE `entry` = 40236;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Strahad Farsan','斯坦哈德·法尔杉') WHERE `entry` = 40237;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Makrinni Scrabbler','玛科尼快钳龙虾人') WHERE `entry` = 40243;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Liott Maneskin','利奥特·鬃皮') WHERE `entry` = 40248;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Liott Maneskin','利奥特·鬃皮') WHERE `entry` = 40249;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Liott Maneskin','利奥特·鬃皮') WHERE `entry` = 40250;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Embergut','烬腹'), `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Embergut','烬腹') WHERE `entry` = 40258;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Liott Maneskin','利奥特·鬃皮'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Liott Maneskin','利奥特·鬃皮') WHERE `entry` = 40261;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Tidelord Hakash','海潮之王哈凯仕'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Tidelord Hakash','海潮之王哈凯仕') WHERE `entry` = 40276;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Vathras Millson','瓦瑟拉斯·米尔森') WHERE `entry` = 40278;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Katokar Bladewind','卡托卡·刀风') WHERE `entry` = 40289;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Malyfous Darkhammer','玛雷弗斯·暗锤') WHERE `entry` = 40299;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Shailiea','莎莉恩') WHERE `entry` = 40300;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Ralathius','拉拉修斯') WHERE `entry` = 40957;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Buthok Cloudhorn','布托克·云角') WHERE `entry` = 40985;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Parnabus','帕纳布斯') WHERE `entry` = 41014;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Great Cat Spirit','巨豹之灵') WHERE `entry` = 41030;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Cenerron','赛纳隆') WHERE `entry` = 41047;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Reas','瑞亚斯') WHERE `entry` = 41099;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Rayne','莱茵') WHERE `entry` = 41101;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Kex Blowmaster','凯科斯·击王') WHERE `entry` = 41102;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Kex Blowmaster','凯科斯·击王') WHERE `entry` = 41104;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Cannoneer Rileson','炮兵莱尔森') WHERE `entry` = 41122;
UPDATE `locales_quest` SET `ObjectiveText2_loc4` = REPLACE(`ObjectiveText2_loc4`,'Holly Tallhair','霍莉·云鬓') WHERE `entry` = 50328;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(REPLACE(`Objectives_loc4`,'Edwin Harly','艾德温·哈里'),'Basil Frye','巴兹尔·弗莱伊') WHERE `entry` = 70040;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Brother Crowley','克罗雷修士') WHERE `entry` = 80708;
