-- Replace residual English names in zhCN quest text for entities structurally associated with that quest.
-- Entity scope: creature objectives/givers/takers, gameobject objectives/givers/takers, requested/source/reward items.
-- Only names with exactly one existing zhCN localization inside the task relation set are changed.

UPDATE `locales_quest` SET `EndText_loc4` = REPLACE(`EndText_loc4`,'Disarming Mixture','拆弹剂') WHERE `entry` = 280;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Fel Moss','魔苔'), `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Fel Moss','魔苔') WHERE `entry` = 459;
UPDATE `locales_quest` SET `ObjectiveText3_loc4` = REPLACE(`ObjectiveText3_loc4`,'Hillsbrad Proclamation','希尔斯布莱德宣言') WHERE `entry` = 532;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Ambercorn','琥珀颗粒') WHERE `entry` = 771;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Burning Blade Medallion','火刃奖章') WHERE `entry` = 794;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Symbol of Life','生命符记') WHERE `entry` = 1789;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Egg-O-Matic','测蛋器') WHERE `entry` = 2741;
UPDATE `locales_quest` SET `ObjectiveText2_loc4` = REPLACE(`ObjectiveText2_loc4`,'Sharpbeak''s Cage','沙普比克的笼子') WHERE `entry` = 2994;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Morrowgrain','晨光麦') WHERE `entry` = 3792;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Morrowgrain','晨光麦') WHERE `entry` = 3803;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Morrowgrain','晨光麦') WHERE `entry` = 3804;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(REPLACE(`Objectives_loc4`,'Videre Elixir','视灵药剂'),'Evoroot','灵根草') WHERE `entry` = 4041;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Lesser Nether Essence','次级虚空精华') WHERE `entry` = 4107;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Wildkin E''ko','枭兽魂精') WHERE `entry` = 4807;
UPDATE `locales_quest` SET `ObjectiveText3_loc4` = REPLACE(`ObjectiveText3_loc4`,'Remains of Lucien Sarkhoff','卢森·萨克霍夫的遗体') WHERE `entry` = 5382;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Fiery Core','炽热之核') WHERE `entry` = 6643;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Stormpike Assault Orders','雷矛突击令') WHERE `entry` = 6846;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Frostwolf Assault Orders','霜狼突击令') WHERE `entry` = 6901;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Coal','煤块') WHERE `entry` = 7736;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Arena Master','竞技场高手饰物') WHERE `entry` = 7838;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Silverwing Talisman of Merit','银翼功勋奖章') WHERE `entry` = 7886;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Silverwing Talisman of Merit','银翼功勋奖章') WHERE `entry` = 7887;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Silverwing Talisman of Merit','银翼功勋奖章') WHERE `entry` = 7888;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Coarse Weightstone','粗制平衡石') WHERE `entry` = 7889;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Silverwing Talisman of Merit','银翼功勋奖章') WHERE `entry` = 7921;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Warsong Mark of Honor','战歌荣誉奖章') WHERE `entry` = 7922;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Warsong Mark of Honor','战歌荣誉奖章') WHERE `entry` = 7923;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Warsong Mark of Honor','战歌荣誉奖章') WHERE `entry` = 7924;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Warsong Mark of Honor','战歌荣誉奖章') WHERE `entry` = 7925;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Lesser Darkmoon Prize','中级暗月奖品') WHERE `entry` = 7932;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Last Year''s Mutton','去年的羊肉') WHERE `entry` = 7936;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Amulet of the Darkmoon','暗月护符') WHERE `entry` = 7981;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8081;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Kezan''s Taint','科赞的玷污') WHERE `entry` = 8107;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Kezan''s Taint','科赞的玷污') WHERE `entry` = 8108;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Kezan''s Taint','科赞的玷污'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Kezan''s Taint','科赞的玷污') WHERE `entry` = 8109;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Vision of Voodress','巫毒幻象') WHERE `entry` = 8117;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8124;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8157;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8158;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8159;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8163;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8164;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Arathi Resource Crate','阿拉希资源箱') WHERE `entry` = 8165;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Dezian Queenfish','迪森皇后鱼') WHERE `entry` = 8224;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Arthas'' Tears','阿尔萨斯之泪') WHERE `entry` = 8509;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Red Scepter Shard','红色节杖碎片') WHERE `entry` = 8730;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Green Scepter Shard','绿色节杖碎片') WHERE `entry` = 8741;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Egg-O-Matic','测蛋器') WHERE `entry` = 8893;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Dreadnaught Bracers','无畏护腕') WHERE `entry` = 9042;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Redemption Wristguards','救赎腕甲') WHERE `entry` = 9050;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Cryptstalker Wristguards','地穴追猎者护腕') WHERE `entry` = 9061;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Dreamwalker Wristguards','梦游者护腕') WHERE `entry` = 9093;
UPDATE `locales_quest` SET `ObjectiveText2_loc4` = REPLACE(`ObjectiveText2_loc4`,'Writ of Safe Passage','通行文书') WHERE `entry` = 9165;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Sanv Charm','桑维护身符') WHERE `entry` = 40027;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Azure Scale','青铜鳞片') WHERE `entry` = 40062;
UPDATE `locales_quest` SET `Details_loc4` = REPLACE(`Details_loc4`,'Great Virtue','圣洁之书') WHERE `entry` = 40153;
UPDATE `locales_quest` SET `Title_loc4` = REPLACE(`Title_loc4`,'Gobcrank Flazwanger','弗朗兹旺格曲柄'), `Details_loc4` = REPLACE(`Details_loc4`,'Gobcrank Flazwanger','弗朗兹旺格曲柄'), `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Gobcrank Flazwanger','弗朗兹旺格曲柄') WHERE `entry` = 40177;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Jadefire Felhorn','碧火地狱之角') WHERE `entry` = 40211;
UPDATE `locales_quest` SET `OfferRewardText_loc4` = REPLACE(`OfferRewardText_loc4`,'Eldara Relay-Orb','艾尔达拉转移宝珠') WHERE `entry` = 40244;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Heavy Kodo Meat','科多兽肉') WHERE `entry` = 40619;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Elemental Air','元素空气') WHERE `entry` = 40631;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Dream Dust','梦境之尘') WHERE `entry` = 40739;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Blackheart Necklace','黑心项链') WHERE `entry` = 40982;
UPDATE `locales_quest` SET `RequestItemsText_loc4` = REPLACE(`RequestItemsText_loc4`,'Eye of Xythos','克西索斯之眼') WHERE `entry` = 40993;
UPDATE `locales_quest` SET `Objectives_loc4` = REPLACE(`Objectives_loc4`,'Nexus Crystal','连结水晶') WHERE `entry` = 41776;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Intact Human Head','完整的人类头颅') WHERE `entry` = 50002;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Intact Orc Head','完整的兽人头颅') WHERE `entry` = 50004;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Snowball','雪球') WHERE `entry` = 50330;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(REPLACE(`ObjectiveText1_loc4`,'Flawless Draenethyst Sphere','无暇的德莱尼水晶球'),'Righteous Orb','正义宝珠'), `ObjectiveText2_loc4` = REPLACE(`ObjectiveText2_loc4`,'Flawless Draenethyst Sphere','无暇的德莱尼水晶球') WHERE `entry` = 60036;
UPDATE `locales_quest` SET `ObjectiveText1_loc4` = REPLACE(`ObjectiveText1_loc4`,'Teresa''s Copper Coin','特蕾莎的铜币') WHERE `entry` = 60050;
